### ISSUE TITLE
UMD tests not passing for Node 10 and above

### ISSUE THREAD

**Issue by mikeng13** [optimizely/javascript-sdk#222]
Currently, we have to run the `umdbrowser` tests on Node 8.

Running on Node 10 yields this error:

`> @optimizely/optimizely-sdk@3.0.0 test-xbrowser /home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk
> karma start karma.bs.conf.js --single-run
14 02 2019 18:53:27.791:ERROR [config]: Invalid config file!
  ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:137:5)
    at require (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:137:5)
    at require (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/home/travis/build/optimizely/javascript-sdk/packages/optimizely-sdk/node_modules/fstream/node_modules/graceful-fs/fs.js:1:99)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @optimizely/optimizely-sdk@3.0.0 test-xbrowser: `karma start karma.bs.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @optimizely/optimizely-sdk@3.0.0 test-xbrowser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-02-14T18_53_27_811Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @optimizely/optimizely-sdk@3.0.0 test-ci: `npm run test-xbrowser && npm run test-umdbrowser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @optimizely/optimizely-sdk@3.0.0 test-ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-02-14T18_53_27_831Z-debug.log`

**Comment by jordangarcia** [comment]
@mikeng13 can this be closed?

**Comment by mjc1283** [comment]
I believe this was fixed by https://github.com/optimizely/javascript-sdk/pull/433.
