### ISSUE TITLE
[BUG] Test bug report

### ISSUE THREAD

**Issue by mikechu-optimizely** [optimizely/javascript-sdk#842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

3.19.29.4-alpha

### Current Behavior

The SDK doesn't do what I want.

### Expected Behavior

It should know what I want.

### Steps To Reproduce

1. Tell it what you want.
2. Tap the screen.
3. Ask it again for what you want.
4. Wait 37 minutes.
5. Eat a snack.
6. Report a test bug using @yasirfolio3 's amazing form.

### SDK Type

Node

### Node Version

v12 LTS

### Browsers impacted

All of'em

### Link

https://example.com

### Logs

Error: Cannot read property 'value' of undefined
    at doSomething (file.ts:10:20)
    at mainFunction (file.ts:5:10)
    at Object.<anonymous> (file.ts:2:1)

### Severity

Blocking development, Affecting users

### Workaround/Solution

Reboot the machine, then it worked.

### Recent Change

We just started using Optimizely.

### Conflicts

Conflicts with what I want.

**Comment by mikechu-optimizely** [comment]
It can't read your mind....yet.
